version: '3'

services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercur-storefront
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MEDUSA_BACKEND_URL=http://localhost:9000
      - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_test_publishable_key
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_DEFAULT_REGION=pl
      - NEXT_PUBLIC_STRIPE_KEY=pk_test_stripe_key
      - REVALIDATE_SECRET=supersecret
      - NEXT_PUBLIC_SITE_NAME=Fleek Marketplace
      - NEXT_PUBLIC_SITE_DESCRIPTION=Fleek Markeplace
      - NEXT_PUBLIC_ALGOLIA_ID=algolia_id
      - NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=algolia_search_key
    restart: unless-stopped
    networks:
      - mercur-network

networks:
  mercur-network:
    driver: bridge
